// Code generated by protoc-gen-go. DO NOT EDIT.
// source: langd.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	langd.proto

It has these top-level messages:
	EmptyRequest
	EmptyReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto1.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EmptyReply struct {
}

func (m *EmptyReply) Reset()                    { *m = EmptyReply{} }
func (m *EmptyReply) String() string            { return proto1.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()               {}
func (*EmptyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto1.RegisterType((*EmptyReply)(nil), "proto.EmptyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Langd service

type LangdClient interface {
	Shutdown(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	Startup(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyReply, error)
}

type langdClient struct {
	cc *grpc.ClientConn
}

func NewLangdClient(cc *grpc.ClientConn) LangdClient {
	return &langdClient{cc}
}

func (c *langdClient) Shutdown(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := grpc.Invoke(ctx, "/proto.Langd/Shutdown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *langdClient) Startup(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := grpc.Invoke(ctx, "/proto.Langd/Startup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Langd service

type LangdServer interface {
	Shutdown(context.Context, *EmptyRequest) (*EmptyReply, error)
	Startup(context.Context, *EmptyRequest) (*EmptyReply, error)
}

func RegisterLangdServer(s *grpc.Server, srv LangdServer) {
	s.RegisterService(&_Langd_serviceDesc, srv)
}

func _Langd_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LangdServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Langd/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LangdServer).Shutdown(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Langd_Startup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LangdServer).Startup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Langd/Startup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LangdServer).Startup(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Langd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Langd",
	HandlerType: (*LangdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _Langd_Shutdown_Handler,
		},
		{
			MethodName: "Startup",
			Handler:    _Langd_Startup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "langd.proto",
}

func init() { proto1.RegisterFile("langd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x49, 0xcc, 0x4b,
	0x4f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x7c, 0x5c, 0x3c, 0xae,
	0xb9, 0x05, 0x25, 0x95, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0x3c, 0x5c, 0x5c, 0x50,
	0x7e, 0x41, 0x4e, 0xa5, 0x51, 0x11, 0x17, 0xab, 0x0f, 0x48, 0x8f, 0x90, 0x09, 0x17, 0x47, 0x70,
	0x46, 0x69, 0x49, 0x4a, 0x7e, 0x79, 0x9e, 0x90, 0x30, 0xc4, 0x04, 0x3d, 0x64, 0x7d, 0x52, 0x82,
	0xa8, 0x82, 0x05, 0x39, 0x95, 0x4a, 0x0c, 0x42, 0xc6, 0x5c, 0xec, 0xc1, 0x25, 0x89, 0x45, 0x25,
	0xa5, 0x05, 0xc4, 0x6b, 0x4a, 0x62, 0x03, 0x8b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda,
	0x6d, 0x0f, 0xc9, 0xae, 0x00, 0x00, 0x00,
}
